image: python:3.8

variables:
  SECRET_KEY: "SECRET_KEY"
  ENV_NAME: "devops"
  DATABASE_URL: "DATABASE_URL"

stages:
  - install
  - linter
  - unit_testing
  - sonar_qube

install:
  stage: install
  before_script:
    - pip install virtualenv
    - virtualenv env
  script:
    - env
    - source env/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - env

linter:
  stage: linter
  script:
    - source env/bin/activate
    - flake8 --verbose .

unit_testing:
  stage: unit_testing
  script:
    - source env/bin/activate
    - python manage.py test
